from app.decision.engine import make_decision


class DecisionStage:

    def run(self, session):

        print("Running Decision Stage")

        # Strategy rules generated by StrategyEngine
        rules = getattr(session, "strategy_rules", {})

        # Base decision
        session.decision = make_decision(
            session.confluence
        )

        # -----------------------------
        # Strategy-aware Decision
        # -----------------------------

        session.decision["strategy"] = session.strategy

        if session.strategy == "TREND":

            session.decision["minimum_rr"] = rules.get(
                "minimum_rr",
                2.0
            )

            session.decision["allow_counter_trend"] = False

        elif session.strategy == "RANGE":

            session.decision["minimum_rr"] = rules.get(
                "minimum_rr",
                1.5
            )

            session.decision["allow_counter_trend"] = True

        elif session.strategy == "BREAKOUT":

            session.decision["minimum_rr"] = rules.get(
                "minimum_rr",
                2.5
            )

            session.decision["breakout_required"] = True

        elif session.strategy == "REVERSAL":

            session.decision["minimum_rr"] = rules.get(
                "minimum_rr",
                3.0
            )

            session.decision["reversal_required"] = True

        return session